### ISSUE TITLE
Saving System

### ISSUE THREAD

**Issue by andrewcgraves** [COMP350-Fall2022/ArtemisFission#10]
### Description
_______________________________________________________________________________________________________________________________________________
The saving system. Includes a save feature so the player could return to the game at another time. 

### ✏️Tasks✏️
_______________________________________________________________________________________________________________________________________________
- [ ] Save resources and employees
- [ ] Save Contracts 
- [ ] Save and Continue
- [ ] Save and Quit

- [ ] After title screen, there is a save slot menu

- [ ] New Game/Continue game/Load Game feature

- [ ] Three available slots
