### ISSUE TITLE
Start Menu

### ISSUE THREAD

**Issue by Frances637** [COMP350-Fall2022/ArtemisFission#16]
### Description
_______________________________________________________________________________________________________________________________________________
When the game is launched, the program directs to a title screen. 

### ✏️Tasks✏️
_______________________________________________________________________________________________________________________________________________

- [ ] Title screen art
- [ ] Transition between title screen and player screen
- [ ] Single Player or Multi Player option screen
- [ ] User directed here when the game is open
