### ISSUE TITLE
Employee System

### ISSUE THREAD

**Issue by andrewcgraves** [COMP350-Fall2022/ArtemisFission#8]
### Description
Status (current sallery, productivity, moral, specialties optional), ID pic, name, hire/fire

### ✏️ Tasks ✏️
- [ ] Employee Creation (names, attributes, etc)
- [ ] Employee Hire & Fire
- [ ] Max amount of employees

Story Points: 3
